version: "3.9"
services:
  web:
    image: jmixtest/jmix-p:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: jmix-pm-dev
      POSTGRES_USER: jmix
      POSTGRES_PASSWORD: jmix